name = "sidm-api"
account_id = "32bfc61a13bba1ca28035356a20b2491"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "sidm-db"
database_id = "670c2066-ce6f-4fd0-bf96-fc8f5b6ba967"
